apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  labels:
    service: {{ .Release.Name }}

spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.service.port.port_number }}
    targetPort: {{ .Values.container.port }}
    name: {{ .Release.Name }}-http
  selector:
    app: {{ .Release.Name }}